### PR TITLE
Added configurable deadband to potentiometer class

### PR DESCRIPTION
**Pull request by OlHall**
The Potentiometer constructor provides for an optional "deadband"
argument.  Updates will only be sent if the new value falls outside +/-
this deadband value.

### CODE REVIEW

**Comment by OlHall** [comment]
I'm new to GitHub, so excuse me if I've done this wrong, but I've committed a new, different, change and I'm not sure if that's automatically munged it together with the first pull request, or I need to create a new one?!  If that's the case, I don't seem to be able to do it!

**Comment by jboecker** [comment]
It's in the same pull request. I'll try to take a look and merge this before the weekend.

**Comment by OlHall** [comment]
Is this going anywhere or should I branch my own version?

**Comment by jboecker** [comment]
I will definitely merge it before releasing the next version of the Arduino library.
Unfortunately, I haven't had much time to work on DCS-BIOS in the last weeks, especially where it involved testing on actual hardware.

**Comment by OlHall** [comment]
Cool - I'll keep working on it in that case ;-)
BTW - if there's anything you don't agree with (e.g. naming the IntegerBuffer to IntegerData) just say - I won't be offended!

**Pull request closed without merging**
